title: "Software Revolution"
description: "group website"

baseurl: "https://laols574@github.io/swrev"
url: "https://laols574@github.io/swrev"

remote_theme: minima

markdown: kramdown

sass:
  style: compressed
