title: "Software Revolution"
description: "group website"

baseurl: "https://laols574@github.io/swrev"
url: "https://laols574@github.io/swrev"

remote_theme: minima
plugins:
  - jekyll-remote-theme


markdown: kramdown

sass:
  style: compressed
