title: "Software Revolution"
email: e.guzmanortega@vu.nl
description: "SWREV group website"

baseurl: "/swrev"
url: "https://laols574@github.io"

theme: minima

markdown: kramdown

sass:
  style: compressed
