title: "Software Revolution"
description: "group website"

baseurl: ""
url: "https://laols574@github.io/swrev"

remote_theme: codebygina/mediumish-theme-jekyll
plugins:
  - jekyll-remote-theme


markdown: kramdown

sass:
  style: compressed
